# Generated by Django 5.0.2 on 2024-06-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Crime', 'Crime'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Adventure', 'Adventure'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Animation', 'Animation')], max_length=50)),
                ('release_date', models.DateField()),
                ('actor', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveIntegerField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
            ],
        ),
    ]
