# Generated by Django 5.0.2 on 2024-07-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_title',
            new_name='movie',
        ),
    ]
